### PR TITLE
Refactor model eos43at

### PR DESCRIPTION
**Pull request by HellenNamulinda**

### CODE REVIEW

**Comment by GemmaTuron** [comment]
@HellenNamulinda 

the tests are failing, please check, there seems to be a dependency issue

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron,
The packages installed successfully, as I added in the [comment here](https://github.com/ersilia-os/eos43at/issues/1#issuecomment-1643039571), 
Even torch is installed; https://github.com/ersilia-os/eos43at/actions/runs/5606270423/job/15192485169?pr=3#step:8:756,  but not seen by the Deep Draph Library(dgl).  yet it works well locally.
```
Detailed error:
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨
Model API eos43at:run did not produce an outputDGL does not detect a valid backend option. Which backend would you like to work with?

Backend choice (pytorch, mxnet or tensorflow): Traceback (most recent call last):
Error message:
  File "/home/runner/eos/repository/eos43at/20230720024131_7E6A30/eos43at/artifacts/framework/predict.py", line 14, in <module>

    from molgrad.net import MPNNPredictor
  File "/home/runner/eos/repository/eos43at/20230720024131_7E6A30/eos43at/artifacts/framework/molgrad/net.py", line 4, in <module>
    from dgl.nn.pytorch import Set2Set
  File "/usr/share/miniconda/envs/eos43at/lib/python3.7/site-packages/dgl/__init__.py", line 8, in <module>
    from .backend import load_backend, backend_name
  File "/usr/share/miniconda/envs/eos43at/lib/python3.7/site-packages/dgl/backend/__init__.py", line 74, in <module>
    load_backend(get_preferred_backend())
  File "/usr/share/miniconda/envs/eos43at/lib/python3.7/site-packages/dgl/backend/__init__.py", line 69, in get_preferred_backend
    backend_name = input("Backend choice (pytorch, mxnet or tensorflow): ").lower()
EOFError: EOF when reading a line
```

Also, @febielin changes failed on [Model Test on PR](https://github.com/ersilia-os/eos1af5/actions/runs/5613528371/job/15209749391?pr=10), though at a different step.

Let me look more into this.

**Comment by GemmaTuron** [comment]
Hi @HellenNamulinda,

Thanks for the details. It works locally but not on the GitHub runner? Perhaps we could check if in codespaces or the likes it works

**Comment by HellenNamulinda** [comment]
Yes it works locally.
I will try in codespaces.

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron,
I used [Colab](https://colab.research.google.com/drive/1MCC9xPwOARK1L0YYeFOkqr28qUgTCMU1?usp=sharing) to clone my fork and used --repo_path to fetch. The model worked well in Colab. [eos43at_colab_fetch_repo.log](https://github.com/ersilia-os/eos43at/files/12156234/eos43at_colab_fetch_repo.log)

For codespaces, despite all packages installing, the model couldn't fetch successfully, giving an error `'NoneType' object is not iterable`. [eos43at_codespaces_fetch.log](https://github.com/ersilia-os/eos43at/files/12156258/eos43at_codespaces_fetch.log). This is an error with codespaces that @febielin and @ZakiaYahya reported last week.
```
00:53:11 | DEBUG    | InputShapeSingle shape: Single
00:53:11 | DEBUG    | API eos43at:run initialized at URL http://127.0.0.1:36605
00:53:11 | DEBUG    | Schema not yet available
00:53:11 | INFO     | No empty output available
00:53:11 | DEBUG    | Meta: None
00:53:11 | DEBUG    | Posting to run
00:53:11 | DEBUG    | Batch size 100
[]
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

'NoneType' object is not iterable
If this error message is not helpful, open an issue at:
 - https://github.com/ersilia-os/ersilia
Or feel free to reach out to us at:
 - hello[at]ersilia.io

If you haven't, try to run your command in verbose mode (-v in the CLI)
 - You will find the console log file in: /root/eos/current.log
```
So, I doubt the problem is with the refactored code since it works well using Colab. 
I would have suggested re-running the action. But since, we can't re-run the workflows now, I will say we first pause it. I will continue examining it though.

**Comment by GemmaTuron** [comment]
Hi @HellenNamulinda 

In the log I see more than once the following line:
```
Collecting torch==1.9.0
Terminated
```
It appears that Torch is not being compiled in codespaces. In local, it works fetching from repo_path or only from run.sh?
Seeing this error and the error on the model testing, I think there is a dependencies problem only, the model is fine

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron, 
Locally, the model works using both run.sh and within ersilia using --repo_path. [43at_local_fetch.log](https://github.com/ersilia-os/eos43at/files/12160085/43at_local_fetch.log)

For [Colab](https://colab.research.google.com/drive/1MCC9xPwOARK1L0YYeFOkqr28qUgTCMU1?usp=sharing), it also works using --repo_path

Could it be due to ram and storage? Maybe we discuss more about it during the meeting today.

**Comment by GemmaTuron** [comment]
Let's check the workflow once we can run it

**Pull request merged**
